// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeWv36U05wgWTV-iJV7jjEDRFm6Dxk_o',
    appId: '1:66121750982:web:59d08ae9b74da5cc457ac7',
    messagingSenderId: '66121750982',
    projectId: 'mishkatdb',
    authDomain: 'mishkatdb.firebaseapp.com',
    storageBucket: 'mishkatdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS96Acu2PQZlTcT-7SlWH98qizTWoINkU',
    appId: '1:66121750982:android:ccd631441e07ee92457ac7',
    messagingSenderId: '66121750982',
    projectId: 'mishkatdb',
    storageBucket: 'mishkatdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzdAF8zfZtP56YNFE8eshyXO_vxiNW6k',
    appId: '1:66121750982:ios:f1d69ce8d9d29368457ac7',
    messagingSenderId: '66121750982',
    projectId: 'mishkatdb',
    storageBucket: 'mishkatdb.appspot.com',
    iosBundleId: 'com.example.mishkat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzdAF8zfZtP56YNFE8eshyXO_vxiNW6k',
    appId: '1:66121750982:ios:23e86c587f028712457ac7',
    messagingSenderId: '66121750982',
    projectId: 'mishkatdb',
    storageBucket: 'mishkatdb.appspot.com',
    iosBundleId: 'com.example.mishkat.RunnerTests',
  );
}
